# Generated by Django 4.2.9 on 2025-07-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='archivo_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='material_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='material_introductorio',
        ),
        migrations.AddField(
            model_name='curso',
            name='contenido',
            field=models.TextField(blank=True, help_text='Contenido del curso', null=True),
        ),
    ]
