# Generated by Django 4.2.9 on 2025-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_material_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncurso',
            name='error_creacion_correo',
            field=models.TextField(blank=True, help_text='Error al crear dirección de correo', null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='error_envio_bienvenida',
            field=models.TextField(blank=True, help_text='Error al enviar correo de bienvenida', null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='fecha_ultimo_intento',
            field=models.DateTimeField(blank=True, help_text='Fecha del último intento de procesamiento', null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='intentos_procesamiento',
            field=models.PositiveIntegerField(default=0, help_text='Número de intentos de procesamiento'),
        ),
    ]
