# Generated by Django 4.2.9 on 2025-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_inscripcioncurso_error_creacion_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncurso',
            name='password_temp',
            field=models.CharField(blank=True, help_text='Contraseña temporal para usuarios nuevos', max_length=100, null=True),
        ),
    ]
