# Generated by Django 4.2.9 on 2025-07-31 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_inscripcioncurso_password_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del criterio', max_length=200)),
                ('objetivo', models.TextField(help_text='Objetivo del criterio')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición del criterio')),
            ],
            options={
                'verbose_name': 'Criterio de Rúbrica',
                'verbose_name_plural': 'Criterios de Rúbrica',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Esperable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(help_text='Nivel de desempeño (ej: Aceptable, Bueno, Excelente)', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción de la expectativa para este nivel')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición del esperable')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esperables', to='home.criteriorubrica')),
            ],
            options={
                'verbose_name': 'Esperable',
                'verbose_name_plural': 'Esperables',
                'ordering': ['orden', 'nivel'],
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la rúbrica', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la rúbrica', null=True)),
                ('objetivo', models.TextField(help_text='Objetivo de la rúbrica')),
                ('aprendizaje_esperado', models.TextField(help_text='Aprendizaje esperado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la rúbrica está activa')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubricas_creadas', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubrica', to='home.evaluacion')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('comentarios_generales', models.TextField(blank=True, help_text='Comentarios generales de la evaluación', null=True)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje total obtenido', max_digits=5, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, help_text='Nota final calculada', max_digits=5, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_rubrica', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='home.rubrica')),
            ],
            options={
                'verbose_name': 'Resultado de Rúbrica',
                'verbose_name_plural': 'Resultados de Rúbricas',
                'ordering': ['-fecha_evaluacion'],
                'unique_together': {('rubrica', 'estudiante')},
            },
        ),
        migrations.AddField(
            model_name='criteriorubrica',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='home.rubrica'),
        ),
        migrations.CreateModel(
            name='PuntajeCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, help_text='Puntaje obtenido en este criterio', max_digits=5)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios específicos para este criterio', null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='home.criteriorubrica')),
                ('esperable_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_asignados', to='home.esperable')),
                ('resultado_rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes_criterios', to='home.resultadorubrica')),
            ],
            options={
                'verbose_name': 'Puntaje de Criterio',
                'verbose_name_plural': 'Puntajes de Criterios',
                'ordering': ['criterio__orden'],
                'unique_together': {('resultado_rubrica', 'criterio')},
            },
        ),
    ]
