# Generated by Django 4.2.9 on 2025-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_criteriorubrica_esperable_rubrica_resultadorubrica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriorubrica',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Puntaje máximo para este criterio', max_digits=5),
        ),
    ]
