# Generated by Django 4.2.9 on 2025-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='archivo_curso',
            field=models.FileField(blank=True, null=True, upload_to='cursos/material_curso/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='archivo_introductorio',
            field=models.FileField(blank=True, null=True, upload_to='cursos/material_introductorio/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_foto',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_titulos',
            field=models.TextField(blank=True, help_text='Títulos y certificaciones del docente', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_trayectoria',
            field=models.TextField(blank=True, help_text='Experiencia y trayectoria profesional del docente', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, help_text='Duración del curso (ej: 8 semanas)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='material_curso',
            field=models.TextField(blank=True, help_text='Material principal del curso', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='material_introductorio',
            field=models.TextField(blank=True, help_text='Material introductorio del curso', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(blank=True, help_text='Modalidad del curso (ej: Online, Presencial, Híbrido)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, help_text='Nivel del curso (ej: Básico, Intermedio, Avanzado)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Requisitos previos para el curso', null=True),
        ),
    ]
