# Generated by Django 4.2.9 on 2025-07-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_criteriorubrica_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='esperable',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Puntaje asociado a este esperable', max_digits=5),
        ),
    ]
