# Generated by Django 4.2.9 on 2025-07-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_curso_archivo_curso_curso_archivo_introductorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videollamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana para la videollamada')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la videollamada')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de la videollamada')),
                ('link_videollamada', models.URLField(help_text='Enlace de la videollamada')),
                ('activa', models.BooleanField(default=True, help_text='Indica si esta videollamada está activa')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la videollamada', max_length=200, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videollamadas', to='home.curso')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('curso', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
