# Generated by Django 4.2.9 on 2025-07-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_videollamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videollamada',
            name='link_videollamada',
            field=models.URLField(blank=True, help_text='Enlace de la videollamada', null=True),
        ),
    ]
