# Generated by Django 4.2.9 on 2025-07-31 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_esperable_puntaje'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultadorubrica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultadorubrica',
            name='esperable',
            field=models.ForeignKey(blank=True, help_text='Esperable específico evaluado en este resultado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_evaluacion', to='home.esperable'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadorubrica',
            unique_together={('rubrica', 'estudiante', 'esperable')},
        ),
    ]
