# Generated by Django 4.2.9 on 2025-07-26 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_videollamada_link_videollamada'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interesado', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='home.curso')),
                ('usuario_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a Curso',
                'verbose_name_plural': 'Inscripciones a Cursos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
