# Generated by Django 4.2.9 on 2025-07-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_resultadorubrica_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultadorubrica',
            unique_together={('rubrica', 'estudiante')},
        ),
        migrations.RemoveField(
            model_name='resultadorubrica',
            name='esperable',
        ),
    ]
