# Generated by Django 4.2.9 on 2025-08-06 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_resultadorubrica_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del recurso', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción del recurso')),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('presentacion', 'Presentación'), ('enlace', 'Enlace'), ('imagen', 'Imagen'), ('audio', 'Audio'), ('otro', 'Otro')], help_text='Tipo de recurso', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto del recurso', null=True, upload_to='recursos/')),
                ('enlace_externo', models.URLField(blank=True, help_text='Enlace externo (si aplica)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el recurso está activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_creados', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='home.evaluacion')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
