# Generated by Django 4.2.9 on 2025-07-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_inscripcioncurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, help_text='Fecha límite para realizar el pago', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del curso', max_digits=10, null=True),
        ),
    ]
