# Generated by Django 4.2.9 on 2025-08-08 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la asignatura', max_length=200)),
                ('codigo', models.CharField(help_text='Código único de la asignatura', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la asignatura', null=True)),
                ('area_conocimiento', models.CharField(blank=True, help_text='Área de conocimiento de la asignatura', max_length=100, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la asignatura está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='asignatura',
            field=models.ForeignKey(blank=True, help_text='Asignatura a la que pertenece este curso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='home.asignatura'),
        ),
    ]
