# Generated by Django 4.2.9 on 2025-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_curso_fecha_limite_pago_curso_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio del curso', max_digits=10, null=True),
        ),
    ]
