# Generated by Django 4.2.9 on 2025-08-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_curso_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del objetivo de aprendizaje', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del objetivo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición del objetivo')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el objetivo está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_aprendizaje', to='home.rubrica')),
            ],
            options={
                'verbose_name': 'Objetivo de Aprendizaje',
                'verbose_name_plural': 'Objetivos de Aprendizaje',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('rubrica', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='criteriorubrica',
            name='objetivo_aprendizaje',
            field=models.ForeignKey(blank=True, help_text='Objetivo de aprendizaje asociado a este criterio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterios', to='home.objetivoaprendizaje'),
        ),
    ]
