# Generated by Django 4.2.9 on 2025-07-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20250727_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='fecha_limite_pago',
            new_name='dias_plazo_pago',
        ),
    ]
