# Generated by Django 4.2.9 on 2025-07-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_fecha_limite_to_dias_plazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias_plazo_pago',
            field=models.IntegerField(help_text='Días de plazo para realizar el pago'),
        ),
    ]
