# Generated by Django 4.2.9 on 2025-08-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_add_objetivos_aprendizaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='aprendizaje_esperado',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='rubrica',
            name='objetivo',
        ),
    ]
