# Generated by Django 4.2.9 on 2025-08-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_rubrica_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriorubrica',
            options={'ordering': ['nombre'], 'verbose_name': 'Criterio de Rúbrica', 'verbose_name_plural': 'Criterios de Rúbrica'},
        ),
        migrations.AlterModelOptions(
            name='esperable',
            options={'ordering': ['nivel'], 'verbose_name': 'Esperable', 'verbose_name_plural': 'Esperables'},
        ),
        migrations.AlterModelOptions(
            name='objetivoaprendizaje',
            options={'ordering': ['nombre'], 'verbose_name': 'Objetivo de Aprendizaje', 'verbose_name_plural': 'Objetivos de Aprendizaje'},
        ),
        migrations.AlterModelOptions(
            name='puntajecriterio',
            options={'verbose_name': 'Puntaje de Criterio', 'verbose_name_plural': 'Puntajes de Criterios'},
        ),
        migrations.RemoveField(
            model_name='criteriorubrica',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='criteriorubrica',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='esperable',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='objetivoaprendizaje',
            name='orden',
        ),
    ]
