# Generated by Django 4.2.9 on 2025-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_curso_dias_plazo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='profile_photos/'),
        ),
    ]
