# Generated by Django 4.2.9 on 2025-08-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_criteriorubrica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esperable',
            options={'ordering': ['puntaje'], 'verbose_name': 'Esperable', 'verbose_name_plural': 'Esperables'},
        ),
    ]
