# Generated by Django 4.2.9 on 2025-07-29 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_customuser_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('participacion', 'Participación'), ('trabajo_practico', 'Trabajo Práctico'), ('presentacion', 'Presentación'), ('otro', 'Otro')], help_text='Tipo de evaluación', max_length=20)),
                ('nombre', models.CharField(help_text='Nombre de la evaluación', max_length=200)),
                ('fecha_evaluacion', models.DateField(help_text='Fecha de evaluación')),
                ('nota_maxima', models.DecimalField(decimal_places=2, help_text='Nota máxima posible', max_digits=5)),
                ('ponderacion', models.DecimalField(decimal_places=2, help_text='Ponderación en porcentaje', max_digits=5)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la evaluación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la evaluación está activa')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='home.curso')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_evaluacion', '-fecha_creacion'],
                'unique_together': {('curso', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Nota obtenida', max_digits=5, null=True)),
                ('retroalimentacion', models.TextField(blank=True, help_text='Retroalimentación para el estudiante', null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('calificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='home.evaluacion')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['-fecha_calificacion'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
    ]
