# Generated by Django 4.2.9 on 2025-09-04 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_esperable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la reunión', max_length=200)),
                ('fecha_reunion', models.DateField(help_text='Fecha de la reunión')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la reunión')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de la reunión')),
                ('link_videollamada', models.URLField(help_text='Enlace de la videollamada')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la reunión', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la reunión está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(help_text='Usuario que organiza la reunión', on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_organizadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(help_text='Usuarios participantes de la reunión', related_name='reuniones_participantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['fecha_reunion', 'hora_inicio'],
            },
        ),
    ]
