# Generated by Django 4.2.9 on 2025-07-29 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_recreate_calificacion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha_inicio', '-fecha_creacion'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_evaluacion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin de la evaluación', null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la evaluación', null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo de la entrega', upload_to='entregas/')),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional del estudiante', null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de entrega')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('tardio', 'Tardío'), ('rechazado', 'Rechazado'), ('aprobado', 'Aprobado')], default='pendiente', help_text='Estado de la entrega', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Fecha de revisión', null=True)),
                ('comentario_revisor', models.TextField(blank=True, help_text='Comentario del revisor', null=True)),
                ('calificacion', models.OneToOneField(blank=True, help_text='Calificación asociada a esta entrega', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='home.calificacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='home.evaluacion')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_entrega'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
    ]
