# Generated by Django 4.2.9 on 2025-07-30 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la clasificación', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la clasificación', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la clasificación está activa')),
            ],
            options={
                'verbose_name': 'Clasificación de Ticket',
                'verbose_name_plural': 'Clasificaciones de Tickets',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del ticket', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema')),
                ('clasificacion', models.CharField(help_text='Clasificación principal del ticket', max_length=100)),
                ('subclasificacion', models.CharField(help_text='Subclasificación del ticket', max_length=100)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Usuario admin/staff asignado al ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soporte', to='home.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_soporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Contenido del comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('es_interno', models.BooleanField(default=False, help_text='Si es True, solo lo ven usuarios admin/staff')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='home.ticketsoporte')),
            ],
            options={
                'verbose_name': 'Comentario de Ticket',
                'verbose_name_plural': 'Comentarios de Tickets',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SubclasificacionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la subclasificación', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la subclasificación', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la subclasificación está activa')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasificaciones', to='home.clasificacionticket')),
            ],
            options={
                'verbose_name': 'Subclasificación de Ticket',
                'verbose_name_plural': 'Subclasificaciones de Tickets',
                'ordering': ['clasificacion', 'nombre'],
                'unique_together': {('clasificacion', 'nombre')},
            },
        ),
    ]
